/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChartRouteImport } from './routes/chart'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as RecordsRouteImport } from './routes/records'
import { Route as ApiPublicEventsRouteImport } from './routes/api/public/events'
import { Route as ApiPublicFeedRouteImport } from './routes/api/public/feed'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChartRoute = ChartRouteImport.update({
  id: '/chart',
  path: '/chart',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordsRoute = RecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEventsRoute = ApiPublicEventsRouteImport.update({
  id: '/api/public/events',
  path: '/api/public/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFeedRoute = ApiPublicFeedRouteImport.update({
  id: '/api/public/feed',
  path: '/api/public/feed',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chart': typeof ChartRoute
  '/plan': typeof PlanRoute
  '/records': typeof RecordsRoute
  '/api/public/events': typeof ApiPublicEventsRoute
  '/api/public/feed': typeof ApiPublicFeedRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chart': typeof ChartRoute
  '/plan': typeof PlanRoute
  '/records': typeof RecordsRoute
  '/api/public/events': typeof ApiPublicEventsRoute
  '/api/public/feed': typeof ApiPublicFeedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chart': typeof ChartRoute
  '/plan': typeof PlanRoute
  '/records': typeof RecordsRoute
  '/api/public/events': typeof ApiPublicEventsRoute
  '/api/public/feed': typeof ApiPublicFeedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chart'
    | '/plan'
    | '/records'
    | '/api/public/events'
    | '/api/public/feed'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chart'
    | '/plan'
    | '/records'
    | '/api/public/events'
    | '/api/public/feed'
  id:
    | '__root__'
    | '/'
    | '/chart'
    | '/plan'
    | '/records'
    | '/api/public/events'
    | '/api/public/feed'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChartRoute: typeof ChartRoute
  PlanRoute: typeof PlanRoute
  RecordsRoute: typeof RecordsRoute
  ApiPublicEventsRoute: typeof ApiPublicEventsRoute
  ApiPublicFeedRoute: typeof ApiPublicFeedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chart': {
      id: '/chart'
      path: '/chart'
      fullPath: '/chart'
      preLoaderRoute: typeof ChartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/records': {
      id: '/records'
      path: '/records'
      fullPath: '/records'
      preLoaderRoute: typeof RecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/events': {
      id: '/api/public/events'
      path: '/api/public/events'
      fullPath: '/api/public/events'
      preLoaderRoute: typeof ApiPublicEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/feed': {
      id: '/api/public/feed'
      path: '/api/public/feed'
      fullPath: '/api/public/feed'
      preLoaderRoute: typeof ApiPublicFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChartRoute: ChartRoute,
  PlanRoute: PlanRoute,
  RecordsRoute: RecordsRoute,
  ApiPublicEventsRoute: ApiPublicEventsRoute,
  ApiPublicFeedRoute: ApiPublicFeedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
